### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by q1240641788** [DavidCai1993/lock.js#12]
执行可执行文件的时候报错
/home/Jacky/NodeJS/app.o: error while loading shared libraries: libnode.so.59: cannot open shared object file: No such file or directory

**Comment by DavidCai1993** [comment]
最新版本已经解决了这个问题，更新（`npm i -g lockjs`）后参照 [README 上的步骤](https://github.com/DavidCai1993/lock.js#update-ld_library_path-linux-user-only)。
