### ISSUE TITLE
Packing is ok，but executable error.

### ISSUE THREAD

**Issue by leeeco610** [DavidCai1993/lock.js#14]
In Mac osx10.13.3,  error ：
  dyld: Library not loaded: @rpath/libnode.59.dylib
  Referenced from: /Users/lihaipeng/projects/test/app.o
  Reason: image not found

In Centos 7.4, error: 
error while loading shared libraries: libnode.so.59: cannot open shared object file: No such file or directory

**Comment by bcatalin** [comment]
added the libnode.so.64 to the LD_LIBRARY_PATH and it worked

**Comment by DavidCai1993** [comment]
@leeeco610 After you install the latest `lockjs` (`npm i -g lockjs`), the problem in MacOS should have been solved, and the way to tackle the issue in CentOS has been added to [README](https://github.com/DavidCai1993/lock.js#update-ld_library_path-linux-user-only).
