### ISSUE TITLE
linker fails

### ISSUE THREAD

**Issue by anotherpaul** [DavidCai1993/lock.js#5]
When trying to generate binary file from .locked file, I get this error:

/usr/bin/ld: cannot find -lnode
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ubuntu 16.04 x64, 
clang 3.8
node v.6.9.1 installed via nvm - maybe that's the issue?

**Comment by LCeryue** [comment]
True,I find the same problem when I use nvm to manager the node.js! If you want to use the lock.js, you should better not use the nvm. While using 'make install' it will install the node libs, but NVM does not!

**Comment by LCeryue** [comment]
Looks like the finally libnode.so path is "/root/.nvm/versions/node/v8.8.1/lib/node_modules/lockjs/dist/8.8.1/shared/libnode.so.tar.gz",but when you go to the floder the libnode.so maybe  is "libnode.so.57",so 
`$ cd /root/.nvm/versions/node/v8.8.1/lib/node_modules/lockjs/dist/8.8.1/shared/ `
if find something like "libnode.so.*",just 
`$ ln -sv libnode.so.57 libnode.so`

**Comment by DavidCai1993** [comment]
Fixed by #9 , closed.
