### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by rborn** [DavidCai1993/lock.js#6]
Hi,

I'm trying to run this on a very simple file - `console.log("something")`  following the next sequence:

~~~
lockjs lock ./ ./index.js ./project.locked
lockjs gen ./project.locked ./a w3g721fw0m6cp4cq2hkm4pldi
./a
~~~
However the output is an array with the script path, the key 😳  and the encrypted string I suppose:
~~~
$ ./a 
[ '/private/tmp/aka/a',
  '3zn8hacrubnr1wvaw60fwdn29',
  '$$$$$$$$$$$$$$$$$$48ee0dc347578e2ac2...'
]
~~~

I'm on osX, any idea? 
Thank you 😊

**Comment by DavidCai1993** [comment]
Hi,

I just ran through the sequence above on my Mac OS X 10.12.5:

```shell
➜  example echo 'console.log("something")' > index.js
➜  example lockjs lock ./ ./index.js ./project.locked
[lockjs] packing "index.js"...
[lockjs] packing "project.locked"...
[lockjs] Done.
[lockjs] Locked file: "./project.locked".
[lockjs] Key: "gbla7zmzqw0u05u88hwljtt9".
➜  example lockjs gen ./project.locked ./a gbla7zmzqw0u05u88hwljtt9
[lockjs] Try to get the latest version of node.js...
[lockjs] Try to find node.js (version: 7.7.1) headers and library in cache...
[lockjs] Find in cache.
[lockjs] Done, executable: "/Users/davidcai/workspace/example/a".
➜  example ./a
something
```

The output seems that the package works pretty well... The situation you met is quiet weird, could you plz give me more information like your Node.js version (mine is `v7.10.0`) and the exact content of the script you try to lock ? Thanks 😊

**Comment by rborn** [comment]
Hi, thank you for the fast reply.
Was somehow my mistake, but this takes me the next question 😁
So the index.js file was
~~~
console.log(process.argv);
~~~
instead of "something" ( I was in the wrong folder, sorry for that)
So it's working.

However do I pass arguments to the compiled app ?

Thanks again 😊

**Comment by DavidCai1993** [comment]
For now those arguments passed to the compiled app will always be overwritten 😢 . If you need to pass some information to the compiled app, you could use environment variable, like `NODE_ENV=production ./a` 😄

**Comment by rborn** [comment]
Ok, thank you 🤗
