### ISSUE TITLE
如何将需要带参数运行的js当作entryPoint传入？

### ISSUE THREAD

**Issue by LCeryue** [DavidCai1993/lock.js#7]
实际需要带参数运行一个js启动程序，比如app.js是启动入口的时候，其中需要
var configs = require(process.argv[2]);
这个configs配置项，来配合运行，改怎么传入entryPoint?

**Comment by DavidCai1993** [comment]
`process.argv` 因为一些内部实现问题所以不是特别可靠，建议这类参数使用环境变量传入：

```shell
TEST_CONFIG=123 ./app.o
```

```js
var configs = require(process.env.TEST_CONFIG) // var configs = require('123')
```

**Comment by LCeryue** [comment]
好的，谢谢
